name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]

    name: Tests on PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"

      - name: Run tests
        run: composer test

  qa:
    runs-on: ubuntu-latest
    name: Code Quality

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, mbstring, zip
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v3"

      - name: Check code style
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

      - name: Check code quality
        run: vendor/bin/phpstan analyze